### PR TITLE
5Greplay without nghttp2 dependency

### PR DESCRIPTION
**Pull request by Frankccv**

### CODE REVIEW

**Review by nhnghia — CHANGES_REQUESTED** [review]
you need to resolve this conflict

**Review by nhnghia — CHANGES_REQUESTED** [review]
you need to resolve this conflict

**Comment by nhnghia** [comment]
@Frankccv  do not upload the generated files which need to be removed:
- the file `.so.c` in `rules` folder
- the log files

**Comment by Frankccv** [comment]
> @Frankccv do not upload the generated files which need to be removed:
> 
> * the file `.so.c` in `rules` folder
> * the log files

Done

**Comment by Frankccv** [comment]
> you need to resolve this conflict

What conflicts?

**Comment by nhnghia** [comment]
## conflict 
- [.github/workflows/c-cpp.yml](https://github.com/Montimage/5Greplay/pull/30/files#diff-a6b2b0a5a900a2b301f746f7bafdce303c6c647e00ade3ee28e8f8ebea11c7a5R12-R16)
- [docs/docs/references/rule/readme.md](https://github.com/Montimage/5Greplay/pull/30/files#diff-4ba04bc5cdb0bf3c4f6de641614d1ac154c1f67ebb3a8e1ad2069c9d2f723ccdR8-R12)
- https://github.com/Montimage/5Greplay/pull/30/files#diff-bcc3d0b8e8474e79f0ccc070c1b0186420612a20d9d62c1b51f31dc552ae3310R4-R10


## files to remove:
- log5GReplay.txt
- log.txt
- pcap/dump.pcap
- pcap/http2replay.pcap

## 

this file [rules/rfc2822utils.h](https://github.com/Montimage/5Greplay/pull/30/files#diff-68d95e68889adbb72ab80f6933390ba4cdd7663e03b291ddc2f9de745ccc4b74) should not be in `rules` folder which should contain only `.xml` files

## 

check the files again to remove any `printf` messages, e.g., [here](https://github.com/Montimage/5Greplay/pull/30/files#diff-1bf70803088f260a6a3419d81f961f1ea601681f728a270edd64e132dbb66d6cR159). You might want to use:
- `log_write( LOG_INFO, "message")` to print an info, e.g., [here](https://github.com/Montimage/5Greplay/blob/369c551119ae656623bae44debc5a2291b0ad9c3/src/main.c#L40)
- `log_write( LOG_ERR, "message")` to print an error, e.g., [here](https://github.com/Montimage/5Greplay/blob/1504e105ebffbd4bd044d6f7b1b272f612035f22/src/lib/mmt_utils.h#L194)

**Pull request closed without merging**
